name: Generate PDF and Publish Release

on:
  push:
    branches:
      - main  # 指定分支，或使用 `*` 表示所有分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Pandoc, LaTeX, and Noto Sans CJK TC
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-plain-generic texlive-lang-chinese
        sudo apt-get install -y fonts-noto-cjk
        wget https://github.com/jgm/pandoc/releases/download/3.5/pandoc-3.5-1-amd64.deb
        sudo dpkg -i ./pandoc-3.5-1-amd64.deb
        curl -L https://www.zotero.org/styles/ieee -o ieee.csl        

    - name: Find and convert report.md to PDF
      run: |
        for dir in $(find . -mindepth 1 -maxdepth 1 -type d); do
          cd "$dir"
          if [ -f "./report.md" ]; then
            foldername=$(basename "$dir")
            filename="${foldername}_313832008_簡蔚驊.pdf"        
            if [ -f "./references.bib" ]; then
              pandoc "./report.md" -o "./$filename" --pdf-engine=xelatex --citeproc \
              --bibliography="./references.bib" --csl=../ieee.csl
            else
              pandoc "./report.md" -o "./$filename" --pdf-engine=xelatex
            fi            
            echo "Generated $dir/$filename"
          fi
          cd ..
        done

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "release-${{ github.sha }}"
        release_name: "Generated PDF Release"
        draft: false
        prerelease: false

    - name: Upload generated PDFs to release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 設置 GH_TOKEN
      run: |
        for pdf in $(find . -name "*_313832008_簡蔚驊.pdf"); do
          gh release upload "release-${{ github.sha }}" "$pdf" --clobber
        done
